[build]
builder = "NIXPACKS"
buildCommand = "cd conduit-next && npm ci && npm install prisma --save-dev && npx prisma generate && npm run build"

[deploy]
startCommand = "cd conduit-next && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
PORT = "3000"
NODE_ENV = "production"
NEXTAUTH_URL = "${RAILWAY_PUBLIC_DOMAIN}"
NEXTAUTH_SECRET = "c2e9ad22fb0d2d70ae0420f781d192747659f3e878ecd27f22958502ff5150f4"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

[[services]]
name = "conduit"
references = ["Postgres"]
