[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
PORT = "3000"
NODE_ENV = "production"

[[services]]
name = "postgres"
type = "postgres"
plan = "free"
envs = { DATABASE_URL = "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}" }
